import { numberToWords } from "@/lib/utils"

export function generateAgreementText({
  formData,
  state,
  stampDuty,
  refNumber,
  startDate,
  endDate,
}: {
  formData: any
  state: any
  stampDuty: number
  refNumber: string
  startDate: Date
  endDate: Date
}) {
  const formatDate = (date: Date) =>
    date.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })

  return `
LEAVE AND LICENCE AGREEMENT
(${state.name} — ${state.governing_act})

Reference No: ${refNumber}
Date: ${formatDate(new Date())}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This Leave and Licence Agreement is entered into on ${formatDate(new Date())}
at ${formData.city}, ${state.name}.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PARTIES

LICENSOR (Landlord):
Name    : ${formData.landlord_name}
Address : ${formData.landlord_address}
Phone   : ${formData.landlord_phone}
ID Type : ${formData.landlord_id_type?.toUpperCase()}
ID No   : ${formData.landlord_id_number}

LICENSEE (Tenant):
Name    : ${formData.tenant_name}
Address : ${formData.tenant_address}
Phone   : ${formData.tenant_phone}
ID Type : ${formData.tenant_id_type?.toUpperCase()}
ID No   : ${formData.tenant_id_number}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROPERTY

Address   : ${formData.property_address}
City      : ${formData.city}, ${state.name}
Type      : ${formData.property_type?.charAt(0).toUpperCase() + formData.property_type?.slice(1)}
Furnished : ${formData.furnished?.charAt(0).toUpperCase() + formData.furnished?.slice(1)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TERMS

Period          : ${formatDate(startDate)} to ${formatDate(endDate)}
Duration        : ${formData.duration_months} months
Monthly Rent    : Rs. ${formData.monthly_rent?.toLocaleString("en-IN")}
                  (Rupees ${numberToWords(formData.monthly_rent)} Only)
Security Deposit: Rs. ${formData.security_deposit?.toLocaleString("en-IN")}
                  (Rupees ${numberToWords(formData.security_deposit)} Only)
Notice Period   : ${formData.notice_period_days} days
Electricity     : Paid by ${formData.electricity_payer?.charAt(0).toUpperCase() + formData.electricity_payer?.slice(1)}
Water           : Paid by ${formData.water_payer?.charAt(0).toUpperCase() + formData.water_payer?.slice(1)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STAMP DUTY

Applicable Stamp Duty (${state.name}): Rs. ${stampDuty.toLocaleString("en-IN")}
Rate: ${state.stamp_duty_formula?.rate}% of total consideration
${state.estamp_available ? "eStamp available online: " + (state.estamp_portal || "SHCIL portal") : "Manual stamp paper required (Bihar)"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SPECIAL CONDITIONS

${formData.special_conditions || "None"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SIGNATURES

LICENSOR (Landlord)              LICENSEE (Tenant)

___________________________      ___________________________
${formData.landlord_name}
Date:                            Date:

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DISCLAIMER
This document was generated by Elvatrixa Legal (elvatrixa.com).
This is a drafting tool, not legal advice. Verify with a qualified
advocate. Document Ref: ${refNumber}
Generated on: ${formatDate(new Date())}
  `.trim()
}
