import type { StateConfig } from "@/types"

export const STATES: StateConfig[] = [
  {
    code: "MH", name: "Maharashtra", name_hi: "Maharashtra", name_mr: "Maharashtra",
    governing_act: "Maharashtra Rent Control Act 1999",
    mta_adopted: false,
    registration_required: "all",
    police_verification_required: true,
    police_verification_portal: "https://tenant.mahapolice.gov.in",
    stamp_duty_formula: { type: "percentage_total_rent", rate: 0.25, min_amount: 100 },
    estamp_available: true,
    estamp_portal: "https://gras.mahakosh.gov.in",
    online_registration: true,
    major_cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane", "Solapur"],
  },
  {
    code: "KA", name: "Karnataka", name_hi: "Karnataka",
    governing_act: "Karnataka Rent Act 1999",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: true,
    police_verification_portal: "https://ksaps.karnataka.gov.in",
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 0.5, min_amount: 500 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Bengaluru", "Mysuru", "Hubli", "Mangaluru", "Belgaum"],
  },
  {
    code: "DL", name: "Delhi", name_hi: "Delhi",
    governing_act: "Delhi Rent Control Act 1958",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: true,
    police_verification_portal: "https://delhipolice.gov.in/tenant-verification",
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 2, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["New Delhi", "Dwarka", "Rohini", "Janakpuri", "Saket"],
  },
  {
    code: "TN", name: "Tamil Nadu", name_hi: "Tamil Nadu", name_ta: "Tamil Nadu",
    governing_act: "Tamil Nadu Rent Control Act 1960",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_total_rent", rate: 1, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
  },
  {
    code: "UP", name: "Uttar Pradesh", name_hi: "Uttar Pradesh",
    governing_act: "UP Rent Control Act 2021",
    mta_adopted: true,
    deposit_cap_months: 2,
    registration_required: "above_11_months",
    police_verification_required: true,
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 4, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Lucknow", "Kanpur", "Agra", "Varanasi", "Noida", "Ghaziabad"],
  },
  {
    code: "RJ", name: "Rajasthan", name_hi: "Rajasthan",
    governing_act: "Rajasthan Rent Control Act 2001",
    mta_adopted: true,
    deposit_cap_months: 2,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 6, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer"],
  },
  {
    code: "KL", name: "Kerala", name_hi: "Kerala",
    governing_act: "Kerala Rent Control Act 1999",
    mta_adopted: true,
    deposit_cap_months: 2,
    registration_required: "above_11_months",
    police_verification_required: true,
    stamp_duty_formula: { type: "percentage_total_rent", rate: 0.25, min_amount: 200 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Kochi", "Thiruvananthapuram", "Kozhikode", "Thrissur"],
  },
  {
    code: "TS", name: "Telangana", name_hi: "Telangana",
    governing_act: "Telangana Rent Control Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: true,
    police_verification_portal: "https://hyderabadpolice.gov.in",
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 4, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar"],
  },
  {
    code: "GJ", name: "Gujarat", name_hi: "Gujarat",
    governing_act: "Gujarat Rent Control Act 1999",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_total_rent", rate: 4.9, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"],
  },
  {
    code: "WB", name: "West Bengal", name_hi: "West Bengal",
    governing_act: "West Bengal Rent Control Act 1997",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: true,
    police_verification_portal: "https://kolkatapolice.gov.in",
    stamp_duty_formula: { type: "percentage_total_rent", rate: 5.5, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri"],
  },
  {
    code: "AP", name: "Andhra Pradesh", name_hi: "Andhra Pradesh",
    governing_act: "Andhra Pradesh Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_total_rent", rate: 0.5, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati"],
  },
  {
    code: "HR", name: "Haryana", name_hi: "Haryana",
    governing_act: "Haryana Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "area_based", rate: 6, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Gurugram", "Faridabad", "Panchkula", "Ambala", "Rohtak"],
  },
  {
    code: "MP", name: "Madhya Pradesh", name_hi: "Madhya Pradesh",
    governing_act: "Madhya Pradesh Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_total_rent", rate: 8, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Bhopal", "Indore", "Gwalior", "Jabalpur"],
  },
  {
    code: "PB", name: "Punjab", name_hi: "Punjab",
    governing_act: "Punjab Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "area_based", rate: 6, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Ludhiana", "Amritsar", "Chandigarh", "Jalandhar", "Patiala"],
  },
  {
    code: "BR", name: "Bihar", name_hi: "Bihar",
    governing_act: "Bihar Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_total_rent", rate: 6, min_amount: 100 },
    estamp_available: false,
    online_registration: false,
    major_cities: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur"],
  },
  {
    code: "OD", name: "Odisha", name_hi: "Odisha",
    governing_act: "Odisha Rent Control Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 5, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Bhubaneswar", "Cuttack", "Rourkela"],
  },
  {
    code: "AS", name: "Assam", name_hi: "Assam",
    governing_act: "Assam Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_total_rent", rate: 8.25, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Guwahati", "Silchar", "Dibrugarh"],
  },
  {
    code: "JH", name: "Jharkhand", name_hi: "Jharkhand",
    governing_act: "Jharkhand Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 5, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"],
  },
  {
    code: "CG", name: "Chhattisgarh", name_hi: "Chhattisgarh",
    governing_act: "Chhattisgarh Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 5, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Raipur", "Bhilai", "Bilaspur"],
  },
  {
    code: "UK", name: "Uttarakhand", name_hi: "Uttarakhand",
    governing_act: "Uttarakhand Rent Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 5, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Dehradun", "Haridwar", "Roorkee", "Nainital"],
  },
  {
    code: "HP", name: "Himachal Pradesh", name_hi: "Himachal Pradesh",
    governing_act: "HP Rent Control Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 5, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Shimla", "Dharamsala", "Manali", "Solan"],
  },
  {
    code: "GA", name: "Goa", name_hi: "Goa",
    governing_act: "Goa Rent Control Act",
    mta_adopted: false,
    registration_required: "above_11_months",
    police_verification_required: false,
    stamp_duty_formula: { type: "percentage_annual_rent", rate: 3, min_amount: 100 },
    estamp_available: true,
    online_registration: false,
    major_cities: ["Panaji", "Margao", "Vasco", "Mapusa"],
  },
]

export const getStateByCode = (code: string) =>
  STATES.find((s) => s.code === code)

export const getStateByName = (name: string) =>
  STATES.find((s) => s.name.toLowerCase() === name.toLowerCase())

export const MTA_STATES = STATES
  .filter((s) => s.mta_adopted).map((s) => s.code)

export const POLICE_VERIFICATION_STATES = STATES
  .filter((s) => s.police_verification_required).map((s) => s.code)

export const ESTAMP_STATES = STATES
  .filter((s) => s.estamp_available).map((s) => s.code)