"use client"

/**
 * HRA Rent Receipt Generator
 * - Completely FREE - loss leader for upsell
 * - HRA compliant - PAN check for rent > Rs.3000/month
 * - Responsive: mobile first
 * - DPDP: no data stored, generated client-side
 */

import { useState } from "react"
import Link from "next/link"

// ── Types ────────────────────────────────────────────────────
interface ReceiptData {
  // Tenant details
  tenant_name: string
  tenant_pan: string
  // Landlord details
  landlord_name: string
  landlord_pan: string
  landlord_address: string
  // Property
  property_address: string
  // Payment
  monthly_rent: number
  payment_month: string
  payment_mode: "cash" | "bank_transfer" | "upi" | "cheque"
  // Optional
  cheque_number?: string
}

const initialForm: ReceiptData = {
  tenant_name: "",
  tenant_pan: "",
  landlord_name: "",
  landlord_pan: "",
  landlord_address: "",
  property_address: "",
  monthly_rent: 0,
  payment_month: "",
  payment_mode: "bank_transfer",
  cheque_number: "",
}

export default function HRAReceiptPage() {
  const [form, setForm] = useState<ReceiptData>(initialForm)
  const [receiptText, setReceiptText] = useState("")
  const [generated, setGenerated] = useState(false)

  // ── Update form field ──────────────────────────────────────
  function update(field: keyof ReceiptData, value: string | number) {
    setForm((prev) => ({ ...prev, [field]: value }))
  }

  // ── PAN required check ─────────────────────────────────────
  // As per Income Tax rules: PAN required if rent > Rs.3000/month
  const panRequired = form.monthly_rent > 3000

  // ── Generate receipt ───────────────────────────────────────
  function generateReceipt() {
    const receiptNo = `RCP-${Date.now().toString().slice(-8)}`
    const today = new Date().toLocaleDateString("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
    })

    const monthYear = form.payment_month
      ? new Date(form.payment_month + "-01").toLocaleDateString("en-IN", {
          month: "long",
          year: "numeric",
        })
      : ""

    const text = `
RENT RECEIPT
(HRA Tax Exemption Compliant)

Receipt No : ${receiptNo}
Date       : ${today}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Received with thanks from:

Tenant Name : ${form.tenant_name}
${panRequired && form.tenant_pan ? `Tenant PAN  : ${form.tenant_pan}` : ""}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PAYMENT DETAILS

Amount    : Rs. ${form.monthly_rent.toLocaleString("en-IN")}/- 
            (Rupees ${form.monthly_rent} Only)
For Month : ${monthYear}
Mode      : ${form.payment_mode.replace("_", " ").toUpperCase()}
${form.payment_mode === "cheque" && form.cheque_number ? `Cheque No : ${form.cheque_number}` : ""}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PROPERTY

Address : ${form.property_address}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

LANDLORD DETAILS

Name    : ${form.landlord_name}
Address : ${form.landlord_address}
${panRequired && form.landlord_pan ? `PAN     : ${form.landlord_pan}` : ""}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

LANDLORD SIGNATURE

___________________________
${form.landlord_name}
Date: ${today}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

IMPORTANT NOTES
1. HRA exemption available ONLY under OLD tax regime
2. PAN mandatory if monthly rent exceeds Rs.3,000
3. Keep this receipt for income tax filing (Form 10BA 
   required if annual rent exceeds Rs.1,00,000)
4. This receipt is valid for HRA claim under 
   Section 10(13A) of Income Tax Act

Generated by Elvatrixa Legal — elvatrixa.com
Receipt No: ${receiptNo}
    `.trim()

    setReceiptText(text)
    setGenerated(true)
  }

  // ── Download receipt ───────────────────────────────────────
  function downloadReceipt() {
    const blob = new Blob([receiptText], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `hra-receipt-${form.payment_month}.txt`
    a.click()
  }

  // ── Reset form ─────────────────────────────────────────────
  function resetForm() {
    setForm(initialForm)
    setReceiptText("")
    setGenerated(false)
  }

  return (
    <div className="max-w-2xl mx-auto px-4 py-6 md:py-10">

      {/* Header */}
      <Link href="/dashboard" className="text-blue-600 text-sm mb-6 block">
        ← Back to Dashboard
      </Link>

      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-gray-900">
            HRA Rent Receipt
          </h1>
          <p className="text-gray-500 text-sm mt-1">
            Free — HRA tax compliant receipt
          </p>
        </div>
        {/* Free badge */}
        <span className="badge-green text-sm px-3 py-1">FREE</span>
      </div>

      {/* HRA info box */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-6">
        <p className="text-blue-800 text-xs font-medium mb-1">
          📋 HRA Tax Rules 2026
        </p>
        <ul className="text-blue-700 text-xs space-y-0.5">
          <li>• HRA exemption available ONLY under OLD tax regime</li>
          <li>• PAN required if monthly rent exceeds Rs.3,000</li>
          <li>• Form 10BA required if annual rent exceeds Rs.1,00,000</li>
          <li>• Landlord signature mandatory on receipt</li>
        </ul>
      </div>

      {!generated ? (
        /* ── Receipt Form ── */
        <div className="space-y-4">

          {/* Tenant details */}
          <div className="card">
            <h2 className="font-semibold text-gray-900 mb-4">Tenant Details</h2>
            <div className="space-y-3">
              <div>
                <label className="label">Your Name (Tenant) *</label>
                <input className="input" type="text"
                  placeholder="As per ID proof"
                  value={form.tenant_name}
                  onChange={(e) => update("tenant_name", e.target.value)} />
              </div>
              {/* PAN required warning */}
              {panRequired && (
                <div>
                  <label className="label">
                    Your PAN *
                    <span className="text-red-500 text-xs ml-1">
                      (Required — rent exceeds Rs.3,000)
                    </span>
                  </label>
                  <input className="input" type="text"
                    placeholder="ABCDE1234F"
                    maxLength={10}
                    value={form.tenant_pan}
                    onChange={(e) => update("tenant_pan", e.target.value.toUpperCase())} />
                </div>
              )}
            </div>
          </div>

          {/* Payment details */}
          <div className="card">
            <h2 className="font-semibold text-gray-900 mb-4">Payment Details</h2>
            <div className="space-y-3">

              <div>
                <label className="label">Monthly Rent (Rs.) *</label>
                <input className="input" type="number"
                  placeholder="e.g. 15000"
                  value={form.monthly_rent || ""}
                  onChange={(e) => update("monthly_rent", Number(e.target.value))} />
                {/* PAN warning */}
                {panRequired && (
                  <p className="text-amber-600 text-xs mt-1">
                    ⚠️ PAN of landlord and tenant required (rent over Rs.3,000)
                  </p>
                )}
              </div>

              <div>
                <label className="label">Payment Month *</label>
                <input className="input" type="month"
                  value={form.payment_month}
                  onChange={(e) => update("payment_month", e.target.value)} />
              </div>

              <div>
                <label className="label">Payment Mode *</label>
                <select className="input" value={form.payment_mode}
                  onChange={(e) => update("payment_mode", e.target.value)}>
                  <option value="bank_transfer">Bank Transfer / NEFT</option>
                  <option value="upi">UPI</option>
                  <option value="cash">Cash</option>
                  <option value="cheque">Cheque</option>
                </select>
              </div>

              {/* Cheque number field */}
              {form.payment_mode === "cheque" && (
                <div>
                  <label className="label">Cheque Number</label>
                  <input className="input" type="text"
                    placeholder="6-digit cheque number"
                    value={form.cheque_number}
                    onChange={(e) => update("cheque_number", e.target.value)} />
                </div>
              )}

            </div>
          </div>

          {/* Property details */}
          <div className="card">
            <h2 className="font-semibold text-gray-900 mb-4">Property Details</h2>
            <div>
              <label className="label">Property Address *</label>
              <textarea className="input min-h-[80px] resize-none"
                placeholder="Full address of rented property"
                value={form.property_address}
                onChange={(e) => update("property_address", e.target.value)} />
            </div>
          </div>

          {/* Landlord details */}
          <div className="card">
            <h2 className="font-semibold text-gray-900 mb-4">Landlord Details</h2>
            <div className="space-y-3">

              <div>
                <label className="label">Landlord Name *</label>
                <input className="input" type="text"
                  placeholder="Landlord full name"
                  value={form.landlord_name}
                  onChange={(e) => update("landlord_name", e.target.value)} />
              </div>

              <div>
                <label className="label">Landlord Address *</label>
                <textarea className="input min-h-[70px] resize-none"
                  placeholder="Landlord permanent address"
                  value={form.landlord_address}
                  onChange={(e) => update("landlord_address", e.target.value)} />
              </div>

              {/* Landlord PAN — required if rent > 3000 */}
              {panRequired && (
                <div>
                  <label className="label">
                    Landlord PAN *
                    <span className="text-red-500 text-xs ml-1">
                      (Required — rent exceeds Rs.3,000)
                    </span>
                  </label>
                  <input className="input" type="text"
                    placeholder="ABCDE1234F"
                    maxLength={10}
                    value={form.landlord_pan}
                    onChange={(e) => update("landlord_pan", e.target.value.toUpperCase())} />
                </div>
              )}

            </div>
          </div>

          {/* Generate button */}
          <button
            className="btn-primary w-full py-3 text-base"
            onClick={generateReceipt}
            disabled={
              !form.tenant_name ||
              !form.landlord_name ||
              !form.landlord_address ||
              !form.property_address ||
              !form.monthly_rent ||
              !form.payment_month ||
              (panRequired && (!form.tenant_pan || !form.landlord_pan))
            }
          >
            Generate Free Receipt
          </button>

          {/* Upsell — create full agreement */}
          <div className="card bg-blue-50 border-blue-200">
            <p className="text-blue-900 text-sm font-medium mb-1">
              Need a full Rental Agreement?
            </p>
            <p className="text-blue-700 text-xs mb-3">
              Generate a legally valid, state-specific rental agreement for just Rs.199
            </p>
            <Link href="/agreements/new/rental"
              className="btn-primary py-2 text-sm inline-block">
              Generate Agreement — Rs.199
            </Link>
          </div>

        </div>
      ) : (
        /* ── Receipt Generated ── */
        <div className="space-y-4">

          {/* Success */}
          <div className="card text-center">
            <div className="text-4xl mb-2">✅</div>
            <h2 className="font-bold text-gray-900">Receipt Generated!</h2>
            <p className="text-gray-500 text-sm mt-1">
              Ready for HRA tax claim
            </p>
          </div>

          {/* Receipt preview */}
          <div className="card">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-semibold text-gray-900">Receipt Preview</h3>
              <button onClick={downloadReceipt}
                className="btn-secondary py-1.5 text-sm">
                Download
              </button>
            </div>
            <pre className="text-xs text-gray-700 whitespace-pre-wrap bg-gray-50 rounded-lg p-4 max-h-80 overflow-y-auto font-mono leading-relaxed">
              {receiptText}
            </pre>
          </div>

          {/* Action buttons */}
          <div className="flex flex-col sm:flex-row gap-3">
            <button onClick={resetForm}
              className="btn-secondary flex-1">
              Generate Another
            </button>
            <Link href="/agreements/new/rental"
              className="btn-primary flex-1 text-center">
              Create Agreement — Rs.199
            </Link>
          </div>

        </div>
      )}

    </div>
  )
}