"use client"

/**
 * NOC Generator Page
 * - No Objection Certificate
 * - Multiple NOC types
 * - Responsive: mobile first
 * - DPDP: no Aadhaar storage
 */

import { useState } from "react"
import Link from "next/link"
import { calculateTotal } from "@/lib/constants"
import PaymentButton from "@/components/ui/payment-button"

// ── NOC Types ────────────────────────────────────────────────
const NOC_TYPES = [
  { value: "police_verification", label: "Police Verification NOC", desc: "For tenant police verification" },
  { value: "tenant_noc",          label: "Tenant NOC",              desc: "Landlord gives NOC to tenant" },
  { value: "property_noc",        label: "Property NOC",            desc: "For property related purposes" },
  { value: "bank_noc",            label: "Bank / Loan NOC",         desc: "For bank loan purposes" },
  { value: "general_noc",         label: "General NOC",             desc: "General purpose NOC" },
]

interface NOCFormData {
  noc_type: string
  // Issuer (who gives NOC)
  issuer_name: string
  issuer_address: string
  issuer_phone: string
  issuer_id_type: string
  issuer_id_number: string
  // Recipient (who receives NOC)
  recipient_name: string
  recipient_address: string
  recipient_phone: string
  // Property
  property_address: string
  city: string
  state: string
  // Purpose
  purpose: string
  valid_until: string
}

const initialForm: NOCFormData = {
  noc_type: "police_verification",
  issuer_name: "",
  issuer_address: "",
  issuer_phone: "",
  issuer_id_type: "pan",
  issuer_id_number: "",
  recipient_name: "",
  recipient_address: "",
  recipient_phone: "",
  property_address: "",
  city: "",
  state: "",
  purpose: "",
  valid_until: "",
}

const STEPS = [
  { number: 1, title: "NOC Type" },
  { number: 2, title: "Issuer" },
  { number: 3, title: "Recipient" },
  { number: 4, title: "Review" },
]

export default function NOCPage() {
  const [step, setStep] = useState(1)
  const [form, setForm] = useState<NOCFormData>(initialForm)
  const [loading, setLoading] = useState(false)
  const [nocText, setNocText] = useState("")
  const [docId, setDocId] = useState("")

  function update(field: keyof NOCFormData, value: string) {
    setForm((prev) => ({ ...prev, [field]: value }))
  }

  const selectedNOCType = NOC_TYPES.find((n) => n.value === form.noc_type)
  const { base, gst, total } = calculateTotal(199)

  // ── Generate NOC text ──────────────────────────────────
  function generateNOCText() {
    const today = new Date().toLocaleDateString("en-IN", {
      day: "numeric", month: "long", year: "numeric",
    })
    const refNo = `NOC-${Date.now().toString().slice(-8)}`

    return `
NO OBJECTION CERTIFICATE (NOC)

Ref No : ${refNo}
Date   : ${today}
Type   : ${selectedNOCType?.label}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TO WHOMSOEVER IT MAY CONCERN

I, ${form.issuer_name}, residing at ${form.issuer_address},
hereby issue this No Objection Certificate in favour of
${form.recipient_name}, residing at ${form.recipient_address}.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PROPERTY DETAILS

Address : ${form.property_address}
City    : ${form.city}, ${form.state}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PURPOSE

${form.purpose || selectedNOCType?.desc}

I have no objection to the above-mentioned person
residing at / using the above property for the
stated purpose.

This NOC is valid until: ${form.valid_until
  ? new Date(form.valid_until).toLocaleDateString("en-IN", {
      day: "numeric", month: "long", year: "numeric"
    })
  : "Further notice"
}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ISSUER DETAILS

Name    : ${form.issuer_name}
Address : ${form.issuer_address}
Phone   : ${form.issuer_phone}
ID Type : ${form.issuer_id_type.toUpperCase()}
ID No   : ${form.issuer_id_number}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIGNATURE

___________________________
${form.issuer_name}
Date: ${today}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Elvatrixa Legal — elvatrixa.com
Ref: ${refNo} | This is a drafting tool, not legal advice.
    `.trim()
  }

  return (
    <div className="max-w-2xl mx-auto px-4 py-6 md:py-10">

      {/* ── Header ── */}
      <Link href="/agreements/new"
        className="text-blue-600 text-sm mb-6 block">
        ← Back
      </Link>
      <h1 className="text-xl md:text-2xl font-bold text-gray-900 mb-2">
        NOC Generator
      </h1>
      <p className="text-gray-500 text-sm mb-6">
        No Objection Certificate — Rs.199
      </p>

      {/* ── Step indicator ── */}
      <div className="flex items-center justify-between mb-8">
        {STEPS.map((s, i) => (
          <div key={s.number} className="flex items-center">
            <div className="flex flex-col items-center">
              <div className={`
                w-8 h-8 rounded-full flex items-center justify-center
                text-sm font-medium
                ${step > s.number ? "bg-green-500 text-white" : ""}
                ${step === s.number ? "bg-blue-700 text-white" : ""}
                ${step < s.number ? "bg-gray-200 text-gray-500" : ""}
              `}>
                {step > s.number ? "✓" : s.number}
              </div>
              <span className="text-xs text-gray-500 mt-1 hidden sm:block">
                {s.title}
              </span>
            </div>
            {i < STEPS.length - 1 && (
              <div className={`
                h-0.5 w-10 md:w-20 mx-1
                ${step > s.number ? "bg-green-500" : "bg-gray-200"}
              `} />
            )}
          </div>
        ))}
      </div>

      {/* ── Step 1: NOC Type ── */}
      {step === 1 && (
        <div className="card">
          <h2 className="font-semibold text-gray-900 mb-4">
            Select NOC Type
          </h2>
          <div className="space-y-3">
            {NOC_TYPES.map((type) => (
              <button key={type.value}
                onClick={() => update("noc_type", type.value)}
                className={`
                  w-full text-left p-4 rounded-lg border transition-colors
                  ${form.noc_type === type.value
                    ? "border-blue-700 bg-blue-50"
                    : "border-gray-200 hover:border-gray-300"
                  }
                `}>
                <p className={`font-medium text-sm
                  ${form.noc_type === type.value
                    ? "text-blue-700" : "text-gray-900"
                  }`}>
                  {type.label}
                </p>
                <p className="text-gray-500 text-xs mt-0.5">{type.desc}</p>
              </button>
            ))}
          </div>

          <div className="mt-4 space-y-3">
            <div>
              <label className="label">Property Address</label>
              <textarea className="input min-h-[70px] resize-none"
                placeholder="Property address for which NOC is issued"
                value={form.property_address}
                onChange={(e) => update("property_address", e.target.value)} />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="label">City</label>
                <input className="input" type="text"
                  placeholder="City"
                  value={form.city}
                  onChange={(e) => update("city", e.target.value)} />
              </div>
              <div>
                <label className="label">State</label>
                <input className="input" type="text"
                  placeholder="State"
                  value={form.state}
                  onChange={(e) => update("state", e.target.value)} />
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── Step 2: Issuer ── */}
      {step === 2 && (
        <div className="card">
          <h2 className="font-semibold text-gray-900 mb-1">
            Issuer Details
          </h2>
          <p className="text-gray-500 text-sm mb-4">
            Person who is giving the NOC
          </p>
          <div className="space-y-4">

            <div>
              <label className="label">Full Name *</label>
              <input className="input" type="text"
                placeholder="As per ID proof"
                value={form.issuer_name}
                onChange={(e) => update("issuer_name", e.target.value)} />
            </div>

            <div>
              <label className="label">Address *</label>
              <textarea className="input min-h-[70px] resize-none"
                placeholder="Issuer address"
                value={form.issuer_address}
                onChange={(e) => update("issuer_address", e.target.value)} />
            </div>

            <div>
              <label className="label">Phone *</label>
              <input className="input" type="tel"
                placeholder="10-digit mobile"
                maxLength={10}
                value={form.issuer_phone}
                onChange={(e) => update("issuer_phone", e.target.value)} />
            </div>

            <div>
              <label className="label">ID Type *</label>
              <select className="input" value={form.issuer_id_type}
                onChange={(e) => update("issuer_id_type", e.target.value)}>
                <option value="pan">PAN Card</option>
                <option value="voter_id">Voter ID</option>
                <option value="passport">Passport</option>
                <option value="driving_licence">Driving Licence</option>
              </select>
            </div>

            <div>
              <label className="label">ID Number *</label>
              <input className="input" type="text"
                placeholder="Enter ID number"
                value={form.issuer_id_number}
                onChange={(e) => update("issuer_id_number", e.target.value)} />
            </div>

          </div>
        </div>
      )}

      {/* ── Step 3: Recipient ── */}
      {step === 3 && (
        <div className="card">
          <h2 className="font-semibold text-gray-900 mb-1">
            Recipient Details
          </h2>
          <p className="text-gray-500 text-sm mb-4">
            Person who will receive the NOC
          </p>
          <div className="space-y-4">

            <div>
              <label className="label">Full Name *</label>
              <input className="input" type="text"
                placeholder="Recipient full name"
                value={form.recipient_name}
                onChange={(e) => update("recipient_name", e.target.value)} />
            </div>

            <div>
              <label className="label">Address *</label>
              <textarea className="input min-h-[70px] resize-none"
                placeholder="Recipient address"
                value={form.recipient_address}
                onChange={(e) => update("recipient_address", e.target.value)} />
            </div>

            <div>
              <label className="label">Phone</label>
              <input className="input" type="tel"
                placeholder="10-digit mobile"
                maxLength={10}
                value={form.recipient_phone}
                onChange={(e) => update("recipient_phone", e.target.value)} />
            </div>

            <div>
              <label className="label">Purpose (Optional)</label>
              <textarea className="input min-h-[70px] resize-none"
                placeholder="Specific purpose of this NOC"
                value={form.purpose}
                onChange={(e) => update("purpose", e.target.value)} />
            </div>

            <div>
              <label className="label">Valid Until (Optional)</label>
              <input className="input" type="date"
                value={form.valid_until}
                onChange={(e) => update("valid_until", e.target.value)} />
            </div>

          </div>
        </div>
      )}

      {/* ── Step 4: Review & Pay ── */}
      {step === 4 && (
        <div className="space-y-4">

          <div className="card">
            <h2 className="font-semibold text-gray-900 mb-4">
              Review Details
            </h2>
            <div className="space-y-2 text-sm">
              {[
                ["NOC Type",   selectedNOCType?.label ?? ""],
                ["Issuer",     form.issuer_name],
                ["Recipient",  form.recipient_name],
                ["Property",   form.property_address],
                ["City/State", `${form.city}, ${form.state}`],
              ].map(([label, value]) => (
                <div key={label}
                  className="flex justify-between py-1.5 border-b border-gray-100 last:border-0">
                  <span className="text-gray-500">{label}</span>
                  <span className="text-gray-900 text-right max-w-[200px]">
                    {value}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Pricing */}
          <div className="card">
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-gray-500">Document fee</span>
                <span>Rs. {base}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">GST (18%)</span>
                <span>Rs. {gst}</span>
              </div>
              <div className="flex justify-between font-bold text-base border-t pt-2 mt-2">
                <span>Total</span>
                <span className="text-blue-700">Rs. {total}</span>
              </div>
            </div>
          </div>

          <PaymentButton
            amount={199}
            planType="retail"
            label="Pay & Generate NOC"
            onSuccess={async (paymentId) => {
              try {
                setLoading(true)
                const text = generateNOCText()
                setNocText(text)
                setDocId(`NOC-${Date.now()}`)
                setStep(5)
              } catch (error) {
                alert("Generation failed.")
              } finally {
                setLoading(false)
              }
            }}
          />

        </div>
      )}

      {/* ── Step 5: Success ── */}
      {step === 5 && (
        <div className="space-y-4">

          <div className="card text-center">
            <div className="text-5xl mb-3">✅</div>
            <h2 className="text-xl font-bold text-gray-900 mb-1">
              NOC Generated!
            </h2>
          </div>

          <div className="card">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-semibold text-gray-900">NOC Preview</h3>
              <button
                onClick={() => {
                  const blob = new Blob([nocText], { type: "text/plain" })
                  const url = URL.createObjectURL(blob)
                  const a = document.createElement("a")
                  a.href = url
                  a.download = `noc-${docId}.txt`
                  a.click()
                }}
                className="btn-secondary py-1.5 text-sm">
                Download
              </button>
            </div>
            <pre className="text-xs text-gray-700 whitespace-pre-wrap bg-gray-50 rounded-lg p-4 max-h-96 overflow-y-auto font-mono leading-relaxed">
              {nocText}
            </pre>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <a href="/dashboard" className="btn-primary text-center flex-1">
              Go to Dashboard
            </a>
            <a href="/agreements/new" className="btn-secondary text-center flex-1">
              Create Another
            </a>
          </div>

        </div>
      )}

      {/* ── Navigation ── */}
      {step < 5 && (
        <div className="flex justify-between mt-6">
          {step > 1 ? (
            <button className="btn-secondary"
              onClick={() => setStep(step - 1)}>
              ← Previous
            </button>
          ) : <div />}
          {step < 4 && (
            <button className="btn-primary"
              onClick={() => setStep(step + 1)}>
              Next →
            </button>
          )}
        </div>
      )}

    </div>
  )
}